CREATE TABLE [dbo].[Person]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [CreationTime] DATETIME2 NOT NULL DEFAULT getDate(), 
    [DeletedTime] DATETIME2 NULL,
	[CompanyId] INT REFERENCES Company(Id) ON UPDATE CASCADE,
	[EmployeeId] INT REFERENCES Employee(Id) ON UPDATE CASCADE,
	CHECK ((CompanyId IS NULL AND EmployeeId IS NOT NULL) OR (CompanyId IS NOT NULL AND EmployeeID IS NULL))
)
GO
CREATE UNIQUE NONCLUSTERED INDEX PersonCompanyUnique ON Person (CompanyId) WHERE CompanyId IS NOT NULL
GO
CREATE UNIQUE NONCLUSTERED INDEX PersonEmployeeUnique ON Person (EmployeeId) WHERE EmployeeId IS NOT NULL